name: WorldGuard
main: worldguard\WorldGuard
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
version: 0.0.2
author: Muqsit
website: https://github.com/Muqsit/WorldGuard
commands:
  worldguard:
  aliases: ["rg", "wg", "region"]
  description: WorldGuard command.
  permission: worldguard.command
  
permissions:
  worldguard.command:
    default: op
    description: Permission to use /rg
    
  
